version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdatabase  # For local testing; replace with your actual URI for production
      - JWT_SECRET=your_secret_key
      - PORT=5000
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      # Ensure your frontend API calls use the container name for the backend service.
      # For example, if you set your API URL in a .env file, you might do:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
